# Workflow Name
name: Template Cleanup

# Trigger the workflow on push events to the master branch
on:
  push:
    branches: [ master ]

# Define jobs
jobs:
  # Cleanup job
  cleanup:
    # Job runs on the latest Ubuntu version
    runs-on: ubuntu-latest

    # Permissions
    permissions:
      contents: write

    # Conditional check
    if: github.repository != 'nekofar/nextjs-lingui-template'

    # Steps instances
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Set up Node.js environment
        uses: actions/setup-node@v3.7.0

      - name: Install pnpm package manager  # Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ^8
          run_install: false

      - name: Clean up the repository
        run: |
          # Declare variables
          NAME="$(basename $GITHUB_REPOSITORY)"
          VERSION='1.0.0-alpha.0'
          
          # Replace package.json name and version fields
          pnpm json -I -f package.json -e "this.name='${NAME}'"
          pnpm json -I -f package.json -e "this.version='${VERSION}'"
          pnpm install --no-frozen-lockfile  # Install dependencies (ignoring lock file)
          
          # Remove unnecessary files
          rm -rf \
            .github/ISSUE_TEMPLATE \
            .github/workflows/template.yml \
            .github/dependabot.yml \
            .github/FUNDING.yml \
            .github/stale.yml \
            CHANGELOG.md
            README.md

      - name: Create Pull Request  # Generate a pull request
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          commit-message: "chore: initial template cleanup"  # Commit message
